FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

# Expose the port for Django development server
EXPOSE 8000

# Default command for Django container
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]