# Generated by Django 5.1.5 on 2025-01-17 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="order_id",),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 17, 11, 36, 9, 942706)
            ),
        ),
    ]
